// ============================================================
// BASE DE DATOS — ST Scent & Textures (151 perfumes)
//
// CÓMO AGREGAR LA FOTO DE UN PERFUME:
// 1. Abrí Tiendanube -> entrá al producto
// 2. Click derecho en la imagen -> "Copiar dirección de imagen"
// 3. Pegá la URL en el campo foto: "" del perfume que corresponda
//
// Si foto queda vacío (""), aparece el frasco CSS automáticamente.
// ============================================================
const PERFUMES = [
  { // DESTACADO en home
    slug:   "your-touch-intense",
    name:   "YOUR TOUCH INTENSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/YOUR TOUCH INTENSE.webp",
    notas_salida:  "Bergamota, Pimienta negra, Azafrán",
    notas_corazon: "Oud, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "your-touch-amber",
    name:   "YOUR TOUCH AMBER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Pimienta roja, Violeta, Enebro",
    notas_corazon: "Canela, Esclarea, Lavanda",
    notas_base:    "Gamuza, Ámbar, Vainilla, Haba tonka",
  },
  {
    slug:   "yeah-parfum",
    name:   "YEAH PARFUM",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Aldehídos, Manzana, Jengibre, Pomelo",
    notas_corazon: "Geranio, Lavanda, Salvia",
    notas_base:    "Incienso, Cedro, Haba tonka, Pachulí",
  },
  { // DESTACADO en home
    slug:   "yeah-man-edp",
    name:   "YEAH MAN EDP",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Manzana, Jengibre",
    notas_corazon: "Salvia, Geranio, Bayas de enebro",
    notas_base:    "Amberwood, Vetiver, Cedro, Haba tonka",
  },
  {
    slug:   "yara-tous",
    name:   "YARA TOUS",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA TOUS.webp",
    notas_salida:  "Mango, Coco, Maracuyá",
    notas_corazon: "Jazmín, Flor del naranjo, Heliotropo",
    notas_base:    "Cachemira, Vainilla, Almizcle",
  },
  {
    slug:   "yara-rosa",
    name:   "YARA ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA ROSA.webp",
    notas_salida:  "Orquídea, Heliotropo, Naranja",
    notas_corazon: "Frutas",
    notas_base:    "Almizcle, Sándalo, Vainilla",
  },
  { // DESTACADO en home
    slug:   "yara-moi",
    name:   "YARA MOI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA MOI.webp",
    notas_salida:  "Jazmín, Durazno",
    notas_corazon: "Ámbar, Caramelo",
    notas_base:    "Pachulí, Sándalo",
  },
  { // DESTACADO en home
    slug:   "yara-elixir",
    name:   "YARA ELIXIR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Frutilla, Grosella negra",
    notas_corazon: "Azahar, Jazmín",
    notas_base:    "Vainilla, Caramelo, Ámbar, Almizcle",
  },
  { // DESTACADO en home
    slug:   "yara-candy",
    name:   "YARA CANDY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Dulce",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA CANDY.webp",
    notas_salida:  "Mandarina verde, Grosella negra",
    notas_corazon: "Gardenia, Frutilla fizz",
    notas_base:    "Sándalo, Vainilla, Almizcle, Ámbar",
  },
  { // DESTACADO en home
    slug:   "vulcan",
    name:   "VULCAN FEU",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "FRENCH AVENUE",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    notas_salida:  "Mango, Limón, Ruibarbo, Jengibre",
    notas_corazon: "Pimienta roja, Jazmín, Praliné, Violeta",
    notas_base:    "Haba Tonka, Musgo, Ámbar gris, Cedro",
  },
  { // DESTACADO en home
    slug:   "vogue-rouge",
    name:   "VOGUE ROUGE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Manzana, Limón",
    notas_corazon: "Violeta, Flor del naranjo, Jazmín",
    notas_base:    "Almizcle, Vainilla, Ámbar",
  },
  { // DESTACADO en home
    slug:   "vogue-night",
    name:   "VOGUE NIGHT",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Notas acuaticas",
    notas_corazon: "Caramelo, Jazmín, Pachulí, Haba tonka",
    notas_base:    "Ámbar gris, Frambuesa, Vainilla, Almizcle",
  },
  { // DESTACADO en home
    slug:   "vintage-radio",
    name:   "VINTAGE RADIO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/VINTAGE RADIO.webp",
    notas_salida:  "Bergamota, Salvia, Lavanda",
    notas_corazon: "Ciruela, Palo santo, Pimienta",
    notas_base:    "Sándalo, Oud",
  },
  {
    slug:   "turathi-electric",
    name:   "TURATHI ELECTRIC",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Pera, Mandarina, Pomelo, Bergamota",
    notas_corazon: "Flor del naranjo, Manzana, Cedro",
    notas_base:    "Almizcle, Vainilla, Ámbar",
  },
  { // DESTACADO en home
    slug:   "turathi-blue",
    name:   "TURATHI BLUE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/TURATHI BLUE.webp",
    notas_salida:  "Cítricos",
    notas_corazon: "Madera, Ámbar",
    notas_base:    "Almizcle, Pachulí, Especias",
  },
  {
    slug:   "toro",
    name:   "TORO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Naranja, Pomelo",
    notas_corazon: "Pimienta, Pelargonio",
    notas_base:    "Vetiver, Benjuí, Cedro, Pachulí",
  },
  { // DESTACADO en home
    slug:   "teriaq-intense",
    name:   "TERIAQ INTENSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/TERIAQ INTENSE.webp",
    notas_salida:  "Azafrán, Bergamota",
    notas_corazon: "Ciruela, Canela",
    notas_base:    "Benjuí, Ámbar, Haba tonka",
  },
  { // DESTACADO en home
    slug:   "shaheen-gold",
    name:   "SHAHEEN GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/SHAHEEN GOLD.webp",
    notas_salida:  "Bergamota, Pimienta rosa, Azafrán",
    notas_corazon: "Rosa, Jazmín, Iris",
    notas_base:    "Oud, Ámbar, Almizcle, Sándalo",
  },
  {
    slug:   "set-yara-mini",
    name:   "SET YARA MINI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "89,100.00",
    price:  "99,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-yara",
    name:   "SET YARA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-dia-de-la-madre",
    name:   "SET DIA DE LA MADRE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "31,500.00",
    price:  "35,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-asad",
    name:   "SET ASAD",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 4 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "sehr",
    name:   "SEHR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/SEHR.webp",
    notas_salida:  "Almendra, Canela",
    notas_corazon: "Jazmín, Pomarose",
    notas_base:    "Vainilla, Haba tonka, Ámbar",
  },
  {
    slug:   "sceptre-malachite",
    name:   "SCEPTRE MALACHITE",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/SCEPTRE MALACHITE.webp",
    notas_salida:  "GROSELLAS NEGRAS, BERGAMOTA",
    notas_corazon: "PIMIENTA ROSA, LAVANDA, ESPECIAS, JAZMÍN",
    notas_base:    "ALMIZCLE, VETIVER, ÁMBAR",
  },
  {
    slug:   "salvo",
    name:   "SALVO",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota",
    notas_corazon: "Pimienta, Nuez moscada, Anís estrellado, Lavanda",
    notas_base:    "Vainilla, Ambroxan",
  },
  {
    slug:   "sakeena",
    name:   "SAKEENA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Maracuyá, Mandarina",
    notas_corazon: "Rosa, Sal, Flor del naranjo, Rosa",
    notas_base:    "Praliné, Almizcle, Vainilla",
  },
  {
    slug:   "rayhaan-tropical-vibe",
    name:   "TROPICAL VIBE RAYHAAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Rayhaan",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "BERGAMOTA, MANGO, ANANÁ",
    notas_corazon: "COCO",
    notas_base:    "VETIVER, SÁNDALO, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "rayhaan-pacific",
    name:   "PACIFIC RAYHAAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Rayhaan",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Limón, Cardamomo",
    notas_corazon: "Lavanda, Ciprés",
    notas_base:    "Ámbar",
  },
  {
    slug:   "rave-now-rosa",
    name:   "RAVE NOW ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/RAVE NOW WOMAN.webp",
    notas_salida:  "Frutos rojos, Naranja",
    notas_corazon: "Jazmín, Lirio de los valles, Malvavisco",
    notas_base:    "Musgo, Vainilla, Almizcle",
  },
  {
    slug:   "ramz-gold",
    name:   "RAMZ GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Azafrán, Pimienta rosa",
    notas_corazon: "Rosa, Jazmín, Oud",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "ramz",
    name:   "RAMZ",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Pera, Bergamota, Lavanda, Menta",
    notas_corazon: "Salvia, Cardamomo",
    notas_base:    "Pachulí, Ámbar, Almizcle, Vainilla",
  },
  {
    slug:   "qaed-untamed",
    name:   "QAED UNTAMED",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/QAED AL FURSAN UNTAMED.webp",
    notas_salida:  "Canela, Cardamomo, Mandarina, Nuez moscada",
    notas_corazon: "Caramelo, Lavanda, Geranio, Esclarea, Ciprés",
    notas_base:    "Ámbar, Cedro, Olíbano, Ládano, Vetiver, Incienso",
  },
  {
    slug:   "qaed-unlimited",
    name:   "QAED UNLIMITED",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "58,500.00",
    price:  "65,000.00",
    foto:   "img/QAED AL FURSAN UNLIMITED.webp",
    notas_salida:  "Coco, Ananá, Cítricos",
    notas_corazon: "Ylang-ylang, Jazmín",
    notas_base:    "Vainilla, Almizcle, Sándalo, Notas dulces",
  },
  {
    slug:   "qaed-al-fursan",
    name:   "QAED AL FURSAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "58,500.00",
    price:  "65,000.00",
    foto:   "img/QAED AL FURSAN.webp",
    notas_salida:  "Ananá, Azafrán",
    notas_corazon: "Abeto, Jazmín",
    notas_base:    "Cedro, Ámbar, Oud",
  },
  {
    slug:   "pistacho",
    name:   "PISTACHO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Anfar",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/PISTACHIO.webp",
    notas_salida:  "Pistacho, Almendra, Caramelo, Postre kunafa",
    notas_corazon: "Haba tonka, Cardamomo",
    notas_base:    "Chocolate, Vainilla, Almizcle, Sándalo",
  },
  {
    slug:   "pisa",
    name:   "PISA",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/PISA.webp",
    notas_salida:  "BERGAMOTA, LIMÓN, NARANJA",
    notas_corazon: "CEDRO",
    notas_base:    "SÁNDALO, ÁMBAR",
  },
  {
    slug:   "philos-rosso",
    name:   "PHILOS ROSSO",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/PHILOS ROSSO.webp",
    notas_salida:  "FRAMBUESA, LIMÓN",
    notas_corazon: "ROSA, JAZMÍN",
    notas_base:    "VAINILLA, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "philos-pura",
    name:   "PHILOS PURA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/PHILOS PURA.webp",
    notas_salida:  "LIMÓN, NARANJA, BERGAMOTA",
    notas_corazon: "FRUTAS",
    notas_base:    "ALMIZCLE, VAINILLA, ÁMBAR",
  },
  {
    slug:   "perseus-exclusif",
    name:   "PERSEUS EXCLUSIF",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Cardamomo, Bergamota, Ají, Heliotropo",
    notas_corazon: "Geranio, Lavanda, Jazmín, Almendra",
    notas_base:    "Madera, Sándalo, Ámbar gris, Vainilla",
  },
  {
    slug:   "perseus",
    name:   "PERSEUS",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Comino, Bergamota, Heliotropo",
    notas_corazon: "Almendra, Lavanda, Jazmín",
    notas_base:    "Ámbar, Sándalo, Vainilla",
  },
  {
    slug:   "opera-rouge",
    name:   "OPERA ROUGE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Cereza, Mandarina",
    notas_corazon: "Té, Flor del Naranjo",
    notas_base:    "Café, Pachulí, Vainilla",
  },
  {
    slug:   "odyssey-revolution",
    name:   "ODYSSEY REVOLUTION",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Piña, Grosellas negras, Slvia",
    notas_corazon: "Vainilla, Ciruela, Cardamomo, Praliné",
    notas_base:    "Haba tonka, Pachulí",
  },
  {
    slug:   "odyssey-bahamas",
    name:   "ODYSSEY BAHAMAS",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Melón, Algas, Sal, Ciruela, Pera",
    notas_corazon: "Notas Acuáticas, Roble, Incienso",
    notas_base:    "Cedro, Azúcar, Ámbar, Almizcle",
  },
  {
    slug:   "odissey-tyrant",
    name:   "ODISSEY TYRANT",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Pomelo",
    notas_corazon: "Geranio, Elemí, Lavanda, Pimienta",
    notas_base:    "Cedro, Vetiver, Ambroxan",
  },
  {
    slug:   "odissey-mega",
    name:   "ODISSEY MEGA MAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "MENTA, BERGAMOTA, NARANJA, JENGIBRE",
    notas_corazon: "ENEBRO, GERANIO, ANANÁ",
    notas_base:    "CEDRO, ALMIZCLE, VETIVER, HABA TONKA",
  },
  {
    slug:   "odissey-mandarin",
    name:   "ODISSEY MANDARIN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/ODYSSEY MANDARIN SKY.webp",
    notas_salida:  "Naranja, Azafrán, Mandarina",
    notas_corazon: "Caramelo, Haba tonka",
    notas_base:    "Ambroxan, Cedro, Vetiver",
  },
  {
    slug:   "odissey-limoni",
    name:   "ODISSEY LIMONI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY LIMONI.webp",
    notas_salida:  "Limón, Mandarina, Bergamota",
    notas_corazon: "Jengibre, Notas marinas, Flor de naranjo",
    notas_base:    "Almizcle, Ámbar",
  },
  {
    slug:   "odissey-homme-white",
    name:   "ODISSEY HOMME WHITE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY HOMME.webp",
    notas_salida:  "Pomelo, Pimienta roja",
    notas_corazon: "Hojas de violeta, Notas marinas",
    notas_base:    "Ámbar, Madera de ámbar",
  },
  {
    slug:   "odissey-homme-negro",
    name:   "ODISSEY HOMME EDP",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY HOMME.webp",
    notas_salida:  "VAINILLA, ÁMBAR",
    notas_corazon: "ESPECIAS, IRIS",
    notas_base:    "CUERO, VAINILLA, JAZMÍN",
  },
  {
    slug:   "odissey-candee",
    name:   "ODISSEY CANDEE",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Frambuesa, Geranio, Durazno, Bergamota",
    notas_corazon: "Caramelo, Jazmín, Maracuyá",
    notas_base:    "Pachulí, Almizcle, Ámbar",
  },
  {
    slug:   "odissey-aqua",
    name:   "ODISSEY AQUA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY AQUA.webp",
    notas_salida:  "Pomelo, Naranja",
    notas_corazon: "Menta, Lavanda",
    notas_base:    "Ambroxan, Ciprés, Pachulí",
  },
  {
    slug:   "odissey-aoud",
    name:   "ODISSEY AOUD",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Intenso",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Azafrán,Nuez moscada, Lavanda",
    notas_corazon: "Madera de Oud",
    notas_base:    "Pachulí, Almizcle, Ambroxan",
  },
  {
    slug:   "nebula-ii",
    name:   "NEBULA II",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Almendra",
    notas_corazon: "Canela, Rosa, Flor del naranjo",
    notas_base:    "Haba tonka, Vainilla, Amberwood",
  },
  {
    slug:   "nebula-i",
    name:   "NEBULA I",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Limón, Pimienta negra",
    notas_corazon: "Iris, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Cedro",
  },
  {
    slug:   "nebras",
    name:   "NEBRAS",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/NEBRAS.webp",
    notas_salida:  "Bayas rojas, Mandarina",
    notas_corazon: "Rosa, Cacao, Vainilla",
    notas_base:    "Ámbar, Azúcar, Almizcle, Haba tonka",
  },
  {
    slug:   "miss-chic",
    name:   "MISS CHIC",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "Frambuesa, Bergamota, Pera, Frutilla, Naranja, Pera",
    notas_corazon: "Peonía, Flor del naranjo, Jazmín",
    notas_base:    "Musgo, Vainilla, Pachulí, Cedro, Ambroxan",
  },
  {
    slug:   "mayar-natural",
    name:   "MAYAR NATURAL",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR NATURAL.webp",
    notas_salida:  "Higo, Melón, Agua de coco",
    notas_corazon: "Jazmín, Flor de loto, Nenúfar",
    notas_base:    "Sándalo, Vainilla, Ambroxan, Almizcle",
  },
  {
    slug:   "mayar-cherry",
    name:   "MAYAR CHERRY",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR CHERRY.webp",
    notas_salida:  "Fresa, Bergamota",
    notas_corazon: "Cacao, Cereza",
    notas_base:    "Pachulí, Vainilla, Ámbar",
  },
  {
    slug:   "mayar",
    name:   "MAYAR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR.webp",
    notas_salida:  "Mandarina, Bergamota, Durazno",
    notas_corazon: "Jazmín, Rosa, Notas florales",
    notas_base:    "Vainilla, Almizcle, Sándalo, Pachulí",
  },
  {
    slug:   "malik-al-tayoor",
    name:   "MALIK AL TAYOOR CONCENTRATED",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Ananá, Manzana",
    notas_corazon: "Escalrea, Hojas de violeta",
    notas_base:    "Cachemira, Ládano",
  },
  {
    slug:   "luxe-emerald",
    name:   "LUXE EMERALD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Peonía, Pomelo, Magnolia, Manzana",
    notas_corazon: "PEONÍA, JAZMÍN, MANZANA VERDE",
    notas_base:    "PRALINÉ, AMBROXAN, MUSGO, ALMIZCLE, VAINILLA",
  },
  {
    slug:   "luxe",
    name:   "LUXE STREET",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "CILANTRO, BERGAMOTA",
    notas_corazon: "MANZANA, VAINILLA, AMBROXAN",
    notas_base:    "ÁMBAR GRIS, HABA TONKA, MADERA",
  },
  {
    slug:   "liquid-brun",
    name:   "LIQUID BRUN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/LIQUID BRUN.webp",
    notas_salida:  "Canela, Bergamota, Flor del naranjo, Cardamomo",
    notas_corazon: "Vainilla, Elemí",
    notas_base:    "Praliné, Ambroxan, Almizcle, Madera",
  },
  {
    slug:   "leonie",
    name:   "LÉONIE",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "LAVANDA, MANDARINA, GROSELLAS NEGRAS",
    notas_corazon: "JAZMÍN, FLOR DEL NARANJO",
    notas_base:    "CEDRO, ALMIZCLE, ÁMBAR GRIS, VAINILLA",
  },
  {
    slug:   "la-voie",
    name:   "LA VOIE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Pimienta rosa, Frambuesa",
    notas_corazon: "Rosa, Iris, Jazmín",
    notas_base:    "Pachulí, Almizcle, Vainilla, Cedro",
  },
  {
    slug:   "la-vivacite",
    name:   "LA VIVACITÉ",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/LA VIVACITÉ.webp",
    notas_salida:  "Grosellas negras, Pera",
    notas_corazon: "Iris, Flor del Naranjo, Jazmín",
    notas_base:    "Haba tonka, Vainilla, Praliné, Pachulí",
  },
  {
    slug:   "kingdom-women",
    name:   "THE KINGDOM WOMEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/THE_KINGDOM_WOMEN.webp",
    notas_salida:  "Pera, Peonía",
    notas_corazon: "Jazmín, Praliné, Haba tonka",
    notas_base:    "Sándalo, Almizcle, Ámbar, Vainilla",
  },
  {
    slug:   "kingdom-man",
    name:   "THE KINGDOM MEN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/THE KINGDOM MAN.webp",
    notas_salida:  "MENTA, LAVANDA",
    notas_corazon: "VAINILLA, TABACO, FLOR DEL NARANJO",
    notas_base:    "BENJUÍ, HABA TONKA",
  },
  {
    slug:   "khanjar",
    name:   "KHANJAR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "112,500.00",
    price:  "125,000.00",
    foto:   "img/KHANJAR.webp",
    notas_salida:  "Nuez moscada, Pimienta, Jengibre",
    notas_corazon: "Cachemira, Pachulí, Violeta",
    notas_base:    "Incienso, Vetiver, Cuero, Almizcle",
  },
  {
    slug:   "khamrah-qawa",
    name:   "KHAMRAH QAWA",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH QAHWA.webp",
    notas_salida:  "Canela, Cardamomo, Jengibre",
    notas_corazon: "Praliné, Frutas confitadas, Flores blancas",
    notas_base:    "Café, Vainilla, Haba tonka, Benjuí, Almizcle",
  },
  {
    slug:   "khamrah-dukhan",
    name:   "KHAMRAH DUKHAN",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH DUKHAN.webp",
    notas_salida:  "Pimienta, Mandarina, Especias",
    notas_corazon: "Incienso, Ládano, Pachulí",
    notas_base:    "Benjuí, Haba tonka, Tabaco, Praliné, Ámbar",
  },
  {
    slug:   "khamrah",
    name:   "KHAMRAH",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH.webp",
    notas_salida:  "Bergamota, Canela",
    notas_corazon: "Flores blancas, Madera de caoba",
    notas_base:    "Vainilla, Ámbar, Benjuí, Mirra",
  },
  {
    slug:   "jorge-di-profumo-aqua",
    name:   "JORGE DI PROFUMO AQUA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Manzana verde, Notas acuáticas, Bergamota",
    notas_corazon: "Ciclamen, Jazmín, Lirio del valle",
    notas_base:    "Ámbar, Cedro, Almizcle, Musgo de roble",
  },
  {
    slug:   "jorge-di-profumo",
    name:   "JORGE DI PROFUMO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Grosella negra",
    notas_corazon: "Rosa, Jazmín, Pachulí",
    notas_base:    "Almizcle, Ámbar, Cedro, Musgo de roble",
  },
  {
    slug:   "jean-lowe-inmortal",
    name:   "JEAN LOWE INMORTAL",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/JEAN LOWE IMMORTEL.webp",
    notas_salida:  "Bergamota, Lavanda, Pimienta negra",
    notas_corazon: "Iris, Violeta, Geranio",
    notas_base:    "Ámbar gris, Cedro, Almizcle",
  },
  {
    slug:   "ishq-al-shuyuk-gold",
    name:   "ISHQ AL SHUYUK GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/ISHQ AL SHUYUK GOLD.webp",
    notas_salida:  "Caramelo, Azafrán",
    notas_corazon: "Cuero, Haba tonka, Gamuza",
    notas_base:    "Ámbar, Almizcle, Vainilla",
  },
  {
    slug:   "ishq-al-shuyuk",
    name:   "ISHQ AL SHUYUK",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "",
    notas_salida:  "Caramelo, Azafrán",
    notas_corazon: "Cuero, Haba tonka, Gamuza",
    notas_base:    "Ámbar, Almizcle, Vainilla",
  },
  {
    slug:   "historic-olmeda",
    name:   "HISTORIC OLMEDA",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "AFNAN",
    perfil: "Versátil",
    promo:  "79,200.00",
    price:  "88,000.00",
    foto:   "",
    notas_salida:  "POMELO, CARDAMOMO, ENEBRO, PIMIENTA ROSA",
    notas_corazon: "BERGAMOTA, CEDRO, NUEZ MOSCADA, JAZMÍN",
    notas_base:    "ALMIZCLE, ÁMBAR GRIS, MANZANA, PACHULÍ",
  },
  {
    slug:   "his-confession",
    name:   "HIS CONFESSION",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/HIS CONFESSION.webp",
    notas_salida:  "Lavanda, Mandarina, Sándalo",
    notas_corazon: "Iris, Benjuí, Ciprés",
    notas_base:    "Haba tonka, Ámbar, Vainilla, Pachulí, Cedro, Incienso",
  },
  {
    slug:   "her-confession",
    name:   "HER CONFESSION",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/HER CONFESSION.webp",
    notas_salida:  "CANELA",
    notas_corazon: "JAZMÍN, INCIENSO, NARDO",
    notas_base:    "ALMIZCLE, VAINILLA, HABA TONKA",
  },
  {
    slug:   "hayaati-rosa",
    name:   "HAYAATI ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Frambuesa, Rosa, Bergamota",
    notas_corazon: "Peonía, Jazmín, Notas florales",
    notas_base:    "Vainilla, Almizcle blanco, Sándalo",
  },
  {
    slug:   "hayaati-al-maleky",
    name:   "HAYAATI AL MALEKY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Manzana, Bergamota, Pimienta rosa",
    notas_corazon: "Iris, Rosa, Notas amaderadas",
    notas_base:    "Vainilla, Ámbar, Almizcle, Cedro",
  },
  {
    slug:   "hayaati",
    name:   "HAYAATI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "img/HAYAATI.webp",
    notas_salida:  "Nuez moscada, Pimienta rosa, Jengibre, Bergamota",
    notas_corazon: "Incienso, Cedro, Ládano, Notas amaderadas",
    notas_base:    "Ámbar, Almizcle, Ámbar gris",
  },
  {
    slug:   "haya",
    name:   "HAYA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/LATAFFA_HAYA.webp",
    notas_salida:  "Fresa, Champagne, Naranja, Rosa",
    notas_corazon: "Gardenia, Jazmín",
    notas_base:    "Sándalo, Ámbar, Castaña",
  },
  {
    slug:   "hawas-ice",
    name:   "HAWAS ICE",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Fresco",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/HAWAS ICE.webp",
    notas_salida:  "Bergamota, Menta, Manzana verde",
    notas_corazon: "Ambroxan, Geranio, Notas acuáticas",
    notas_base:    "Almizcle, Sándalo, Notas amaderadas",
  },
  {
    slug:   "hawas-fire",
    name:   "HAWAS FIRE",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Pimienta rosa, Canela",
    notas_corazon: "Olíbano, Rosa, Pachulí",
    notas_base:    "Vainilla, Ámbar, Almizcle",
  },
  {
    slug:   "hawas-eclat",
    name:   "HAWAS ECLAT",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "85,050.00",
    price:  "94,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Notas acuáticas",
    notas_corazon: "Jazmín, Rosa, Geranio",
    notas_base:    "Almizcle, Cedro, Ámbar",
  },
  {
    slug:   "hawas",
    name:   "HAWAS",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/HAWAS.webp",
    notas_salida:  "Bergamota, Manzana, Canela, Limón",
    notas_corazon: "Ciruela, Cardamomo, Flor del naranjo",
    notas_base:    "Ámbar gris, Almizcle, Pachulí",
  },
  {
    slug:   "glacier-ultra",
    name:   "GLACIER ULTRA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "img/GLACIER ULTRA.webp",
    notas_salida:  "Bergamota, Pomelo, Pimienta rosa",
    notas_corazon: "Geranio, Lavanda, Salvia",
    notas_base:    "Cedro, Almizcle, Ambroxan",
  },
  {
    slug:   "glacier-le-noir",
    name:   "GLACIER LE NOIR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pimienta negra, Bergamota, Cardamomo",
    notas_corazon: "Iris, Violeta, Incienso",
    notas_base:    "Cedro, Ámbar, Almizcle, Cuero",
  },
  {
    slug:   "glacier-bold",
    name:   "GLACIER BOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Coco, Haba tonka, Bergamota",
    notas_corazon: "Ládano, Azafrán, Violeta",
    notas_base:    "Ámbar, Oud, Sándalo, Almizcle blanco",
  },
  {
    slug:   "glacier-bella",
    name:   "GLACIER BELLA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Grosella negra",
    notas_corazon: "Jazmín, Rosa, Notas florales",
    notas_base:    "Almizcle blanco, Cedro, Ámbar",
  },
  {
    slug:   "ghost-spectre",
    name:   "GHOST SPECTRE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "French Avenue",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/GHOST SPECTRE.webp",
    notas_salida:  "JENGIBRE, BERGAMOTA, CARDAMOMO",
    notas_corazon: "ROSA, PIMIENTA ROSA",
    notas_base:    "CEDRO, PACHULÍ, VAINILLA",
  },
  {
    slug:   "gharam",
    name:   "GHARAM",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "Pera, Naranja, Ananá",
    notas_corazon: "Magnolia, Jazmín",
    notas_base:    "Almizcle, Praliné, Ámbar, Praliné",
  },
  {
    slug:   "galactic-marron",
    name:   "GALACTIC MEN INTENSE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "MIEL, TABACO",
    notas_corazon: "VAINILLA, CACAO, PACHULÍ",
    notas_base:    "SÁNDALO, ÁMBAR",
  },
  {
    slug:   "fhakar-women",
    name:   "FHAKAR WOMEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR ROSE.webp",
    notas_salida:  "Azucena, Granada, Aldehídos, Frutas",
    notas_corazon: "Jazmín, Nardos, Rosa, Peonía, Ylang-Ylang",
    notas_base:    "Vainilla, Ambroxan, Sándalo, Almizcle",
  },
  {
    slug:   "fhakar-man",
    name:   "FHAKAR MAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR.webp",
    notas_salida:  "Pomelo, Durazno, Bergamota, Naranja",
    notas_corazon: "Jazmín, Geranio, Rosa, Lychee",
    notas_base:    "Almizcle, Vainilla, Vetiver, Pachulí",
  },
  {
    slug:   "fhakar-gold",
    name:   "FHAKAR GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR EXTRAIT GOLD.webp",
    notas_salida:  "Bergamota, Pomelo, Pimienta rosa",
    notas_corazon: "Rosa, Jazmín, Geranio",
    notas_base:    "Pachulí, Almizcle, Vainilla, Vetiver",
  },
  {
    slug:   "fakhar-platin",
    name:   "FAKHAR PLATIN",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/FAKHAR PLATIN.webp",
    notas_salida:  "Bergamota, Pimienta roja, Cardamomo",
    notas_corazon: "Lavanda, Jengibre, Guayaba",
    notas_base:    "Palo santo, Incienso, Sándalo",
  },
  {
    slug:   "extravagant-lover",
    name:   "EXTRAVAGANT LOVER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pimienta roja, Mandarina",
    notas_corazon: "Jazmín, Rosa, Flor del naranjo",
    notas_base:    "Ámbar, Vainilla",
  },
  {
    slug:   "emeer",
    name:   "EMEER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/EMEER.webp",
    notas_salida:  "Bergamota, Limón, Esclarea",
    notas_corazon: "Sándalo, Te verde, Cardamomo",
    notas_base:    "Cedro, Ámbar gris, Pachulí, Cachemira",
  },
  {
    slug:   "emaan",
    name:   "EMAAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/EMAAN.webp",
    notas_salida:  "Flor del Naranjo, Grosellas negras, Bergamota",
    notas_corazon: "Nardos, Jazmín",
    notas_base:    "Cedro, Pachulí, Vainilla, Almizcle",
  },
  {
    slug:   "eclaire-banoffi",
    name:   "ECLAIRE BANOFFI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "85,050.00",
    price:  "94,500.00",
    foto:   "",
    notas_salida:  "Banana,  Dulce de Leche",
    notas_corazon: "Vainilla, Crema batida",
    notas_base:    "Bizcocho, Praliné, Almizcle",
  },
  {
    slug:   "eclaire",
    name:   "ECLAIRE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ECLAIRE.webp",
    notas_salida:  "Pomelo, Bergamota, Frambuesa",
    notas_corazon: "Rosa, Jazmín, Notas florales",
    notas_base:    "Vainilla, Almizcle, Pachulí, Ámbar",
  },
  {
    slug:   "desirable-addiction",
    name:   "DESIRABLE ADDICTION",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "LIMÓN",
    notas_corazon: "RON, FLOR DEL NARANJO",
    notas_base:    "VAINILLA",
  },
  {
    slug:   "delilah",
    name:   "DELILAH",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/MAISONALHAMBRA-DELILAH.webp",
    notas_salida:  "Ruibarbo, Litchi, Bergamota",
    notas_corazon: "Rosa, Peonía, Azucena",
    notas_base:    "Cachemira, Vainilla, Almizcle",
  },
  {
    slug:   "confidential-platin",
    name:   "CONFIDENTIAL PLATIN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "",
    notas_salida:  "Ciprés, Bergamota, Pimienta",
    notas_corazon: "Notas marinas, Madera",
    notas_base:    "Ládano, Musgo, Ámbar gris, Almizcle",
  },
  {
    slug:   "confidential-gold",
    name:   "CONFIDENTIAL GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/CONFIDENTIAL GOLD.webp",
    notas_salida:  "Maracuyá, Pera, Frambuesa, Durazno",
    notas_corazon: "Lirio del valle",
    notas_base:    "Pachulí, Heliotropo, Vainilla, Almizcle, Sándalo",
  },
  {
    slug:   "checkmate-queen",
    name:   "QUEEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "ARMAF",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "NOTAS VERDES",
    notas_corazon: "ESPECIAS, HIGO",
    notas_base:    "SÁNDALO",
  },
  {
    slug:   "cdn-urban-elixir",
    name:   "CDN URBAN ELIXIR",
    cat:    "Hombre",
    marca:  "Armaf",
    perfil: "Intenso",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/CDN URBAN MAN ELIXIR.webp",
    notas_salida:  "BERGAMOTA, PIMIENTA ROSA, JAZMÍN, FLOR DEL NARANJO",
    notas_corazon: "LAVANDA, VETIVER, GERANIO, AZAFRÁN",
    notas_base:    "ÁMBAR, LÁDANO, PACHULÍ, AMBROXAN",
  },
  {
    slug:   "cdn-untold",
    name:   "CDN UNTOLD",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "94,500.00",
    price:  "105,000.00",
    foto:   "img/ARMAF-CDN_UNTOLD.webp",
    notas_salida:  "Jazmín, Azafrán",
    notas_corazon: "Ámbar gris, Madera de ámbar",
    notas_base:    "Cedro",
  },
  {
    slug:   "cdn-sillage",
    name:   "CDN SILLAGE",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Fresco",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_SILLAGE.webp",
    notas_salida:  "Bergamota, Limón, Grosellas negras, Jengibre",
    notas_corazon: "Iris, Rosa, Jazmín",
    notas_base:    "Almizcle, Sándalo, Cedro, Ambroxán",
  },
  {
    slug:   "cdn-rosa",
    name:   "CDN ROSA",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Naranja, Durazno, Bergamota",
    notas_corazon: "Geranio, Litchi, Rosa, Jazmín",
    notas_base:    "Vetiver, Vainilla, Almizcle, Pachulí",
  },
  {
    slug:   "cdn-precieux",
    name:   "CDN PRECIEUX",
    cat:    "Unisex, Hombre",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "112,500.00",
    price:  "125,000.00",
    foto:   "img/ARMAF-CDN_PRECIEUX.webp",
    notas_salida:  "Caramelo, Pimienta, Pera, Bergamota, Limón,  Piña",
    notas_corazon: "Musgo, Jazmín, Lirio de los valles, Anís",
    notas_base:    "Vainilla, Cuero, Pachulí, Ambroxan, Almizcle",
  },
  {
    slug:   "cdn-milestone",
    name:   "CDN MILESTONE",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Frutos rojos, Bergamota",
    notas_corazon: "Sándalo, Madera, Violeta",
    notas_base:    "Almizcle, Vetiver, Ambroxan",
  },
  {
    slug:   "cdn-maleka",
    name:   "CDN MALEKA",
    cat:    "Mujer",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_MALEKA.webp",
    notas_salida:  "Litchi, Pimienta roja, Bergamora",
    notas_corazon: "Lirio",
    notas_base:    "Praliné, Sándalo, Ambroxan",
  },
  {
    slug:   "cdn-lionheart-women",
    name:   "CDN LIONHEART WOMEN",
    cat:    "Mujer",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "VAINILLA, LAVANDA",
    notas_corazon: "CACAO, JENGIBRE",
    notas_base:    "VAINILLA",
  },
  {
    slug:   "cdn-iconic",
    name:   "CDN ICONIC",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_ICONIC.webp",
    notas_salida:  "Pomelo, Menta, Limón, Pimienta roja, Cilantro",
    notas_corazon: "Melón, Nuez moscada, Jengibre, Jazmín",
    notas_base:    "Cedro,Pachulí, Ládano, Ámbar, Incienso",
  },
  {
    slug:   "club-de-nuit",
    name:   "Club de Nuit",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "85,500.00",
    price:  "95,000.00",
    foto:   "",
    notas_salida:  "Limón, Piña, Bergamota, Manzana, Grosellas negras",
    notas_corazon: "Rosa, Jazmín, Madera",
    notas_base:    "Almizcle, Ámbar gris, Pachulí, Vainilla",
  },
  {
    slug:   "caprice",
    name:   "AL NASHAMA CAPRICE",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Fresco",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/AL NASHAMA CAPRICE.webp",
    notas_salida:  "JENGIBRE, CARDAMOMO, BERGAMOTA, LIMÓN",
    notas_corazon: "LAVANDA, GERANIO, MENTA",
    notas_base:    "ÁMBAR, PACHULÍ",
  },
  {
    slug:   "candid",
    name:   "CANDID",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/MAISONALHAMBRA_CANDID.webp",
    notas_salida:  "BERGAMOTA, ANANÁ",
    notas_corazon: "JAZMÍN, ROSA, FLOR DEL NARANJO",
    notas_base:    "VAINILLA, PACHULÍ, HABA TONKA",
  },
  {
    slug:   "cherry-bouquet",
    name:   "CHERRY BOUQUET",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Afnan",
    perfil: "Dulce",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/AFNAN-CHERRY_BOUQUET.webp",
    notas_salida:  "Cereza negra, Almendra",
    notas_corazon: "Rosa, Jazmín",
    notas_base:    "Vainilla, Vetiver, Cedro, Pachulí",
  },
  {
    slug:   "bharara-king",
    name:   "BHARARA KING",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Bharara",
    perfil: "Versátil",
    promo:  "125,100.00",
    price:  "139,000.00",
    foto:   "img/BHARARA KING.webp",
    notas_salida:  "Bergamota, Ananá, Pimienta negra",
    notas_corazon: "Azafrán, Rosa, Jazmín",
    notas_base:    "Oud, Ámbar, Vainilla, Almizcle",
  },
  {
    slug:   "bharara-chocolate",
    name:   "BHARARA CHOCOLATE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Bharara",
    perfil: "Dulce",
    promo:  "125,100.00",
    price:  "139,000.00",
    foto:   "img/BHARARA CHOCOLATE.webp",
    notas_salida:  "Bergamota, Canela, Cardamomo",
    notas_corazon: "Coñac,Praliné",
    notas_base:    "Almizcle, Haba tonka, Vainilla",
  },
  {
    slug:   "badee-sublime",
    name:   "BADEE SUBLIME",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE_SUBLIME_1.webp",
    notas_salida:  "LITCHI, ROSA, MANZANA",
    notas_corazon: "CIRUELA, JAZMÍN",
    notas_base:    "PACHULÍ, VAINILLA, VETIVER",
  },
  {
    slug:   "badee-oud-for-glory",
    name:   "BADEE OUD FOR GLORY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE OUD FOR GLORY.webp",
    notas_salida:  "Nuez Moscada, Lavanda, Azafrán",
    notas_corazon: "Madera de Oud, Pachulí",
    notas_base:    "Madera de Oud, Almizcle, Pachulí",
  },
  {
    slug:   "badee-noble-blush",
    name:   "BADEE NOBLE BLUSH",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE NOBLE BLUSH.webp",
    notas_salida:  "Leche",
    notas_corazon: "Almendra, Merengue",
    notas_base:    "Vainilla, Sándalo, Almizcle",
  },
  {
    slug:   "badee-honor-y-gloria",
    name:   "BADEE HONOR AND GLORY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE HONOR Y GLORY.webp",
    notas_salida:  "Piña, Créme Brulée",
    notas_corazon: "Canela, Pimienta, Cúrcuma, Benjuí",
    notas_base:    "Sándalo, Musgo, Cachemira, Vainilla",
  },
  {
    slug:   "badee-amethyst",
    name:   "BADEE AMETHYST",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE_AMETHYST_1.webp",
    notas_salida:  "PIMIENTA ROSA, BERGAMOTA",
    notas_corazon: "ROSA, JAZMÍN",
    notas_base:    "OUD, VAINILLA, ÁMBAR",
  },
  {
    slug:   "atlas",
    name:   "ATLAS",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "SAL, LIMÓN",
    notas_corazon: "DAVANA, IRIS",
    notas_base:    "ÁMBAR GRIS, SÁNDALO, MUSGO",
  },
  {
    slug:   "asad-elixir",
    name:   "ASAD ELIXIR",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Pimienta, Cítricos, Limón, Menta",
    notas_corazon: "Canela, Clavo, Jengibre",
    notas_base:    "Madera de ámbar, Madera de guayaco, Cuero",
  },
  {
    slug:   "asad-bourbon",
    name:   "ASAD BOURBON",
    cat:    "Hombre",
    marca:  "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "98,500.00",
    foto:   "img/ASAD BOURBON.webp",
    notas_salida:  "Pimienta rosa, Lavanda, Ciruela",
    notas_corazon: "Cacao, Nuez moscada, Davana",
    notas_base:    "Vetiver, Vainilla, Ámbar",
  },
  {
    slug:   "asad",
    name:   "ASAD",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ASAD.webp",
    notas_salida:  "Pimienta,Piña, Tabaco",
    notas_corazon: "Café, Pachulí, Iris",
    notas_base:    "Ámbar, Vainilla, Madera, Benjuí, Ládano",
  },
  {
    slug:   "art-of-universe",
    name:   "ART OF UNIVERSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ART OF UNIVERSE.webp",
    notas_salida:  "Mandarina, Jengibre, Bergamota, Menta",
    notas_corazon: "Pera, Flor del Naranjo",
    notas_base:    "Almizcle, Ámbar, Cedro",
  },
  {
    slug:   "art-of-nature-i",
    name:   "ART OF NATURE I",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/ART OF NATURE I.webp",
    notas_salida:  "HIGO, CIRUELA",
    notas_corazon: "CUERO, RUIBARBO, ROSA",
    notas_base:    "OUD, ÁMAR GRIS, VAINILLA",
  },
  {
    slug:   "antique",
    name:   "ANTIQUE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ANTIQUE.webp",
    notas_salida:  "Higo, Leche, Cardamomo, Coco",
    notas_corazon: "Vetiver, Iris, Jazmín",
    notas_base:    "Sándalo, Caramelo, Haba tonka, Ámbar, Almizcle",
  },
  {
    slug:   "ansaam-gold",
    name:   "Ansaam Gold",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ANSAAM GOLD.webp",
    notas_salida:  "Mandarina, Pera",
    notas_corazon: "Jazmín, Rosa",
    notas_base:    "Almizcle, Vainilla, Frambuesa",
  },
  {
    slug:   "angham",
    name:   "ANGHAM",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/angham.webp",
    notas_salida:  "Jengibre, Mandarina, Pimienta roja",
    notas_corazon: "Praliné, Cacao, Lavanda, Jazmín",
    notas_base:    "Almizcle, Ámbar, Vainilla",
  },
  {
    slug:   "amber-oud-dubai-nigth",
    name:   "AMBER OUD DUBAI NIGTH",
    cat:    "Unisex",
    marca:  "Al Haramain",
    perfil: "Intenso",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD DUBAI NIGHT.webp",
    notas_salida:  "Lavanda, Azafrán, Bergamota",
    notas_corazon: "Madera de Oud, Lirio de los valles, Rosa",
    notas_base:    "Ámbar, Almizcle, Haba tonka, Vainilla",
  },
  {
    slug:   "9am-pour-femme",
    name:   "9AM pour Femme",
    cat:    "Mujer",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9_AM_POURFEMME_1.webp",
    notas_salida:  "Cidra, Mandarina, Cardamomo, Pimienta rosa",
    notas_corazon: "Manzana verde, Azahar, Lavanda, Rosa",
    notas_base:    "Cedro, Musgo, Almizcle, Pachulí",
  },
  {
    slug:   "amber-oud-aqua",
    name:   "AMBER OUD AQUA",
    cat:    "Unisex, Hombre",
    marca:  "Al Haramain",
    perfil: "Fresco",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD AQUA DUBAI.webp",
    notas_salida:  "Notas acuáticas, Bergamota, Limón",
    notas_corazon: "Geranio, Lavanda, Notas florales",
    notas_base:    "Ámbar, Sándalo, Almizcle",
  },
  {
    slug:   "amber-oud-gold-edition",
    name:   "Amber Oud Gold Edition",
    cat:    "Unisex, Hombre",
    marca:  "Al Haramain",
    perfil: "Intenso",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD GOLD.webp",
    notas_salida:  "Bergamota, Limón, Romero",
    notas_corazon: "Jazmín, Ládano, Notas especiadas",
    notas_base:    "Ámbar, Sándalo, Vainilla, Almizcle",
  },
  {
    slug:   "al-qiam-silver",
    name:   "AL QIAM SILVER",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "88,000.00",
    foto:   "",
    notas_salida:  "POMELO, JENGIBRE",
    notas_corazon: "AMBROXAN, SÁNDALO",
    notas_base:    "ALMIZCLE, VETIVER",
  },
  {
    slug:   "ajwad",
    name:   "AJWAD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "68,000.00",
    foto:   "img/AJWAD.webp",
    notas_salida:  "Azafrán, Nuez moscada, Canela",
    notas_corazon: "Oud, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "9pm-rebel",
    name:   "9PM Rebel",
    cat:    "Unisex, Hombre",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9PM REBEL.webp",
    notas_salida:  "Ananá, Manzana verde, Mandarina",
    notas_corazon: "Vainilla, Cedro, Musgo de roble",
    notas_base:    "Almizcle, Ámbar gris, Caramelo, Maderas secas",
  },
  {
    slug:   "9pm-pour-femme",
    name:   "9PM pour Femme",
    cat:    "Mujer",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "",
    notas_salida:  "Manzana, Lavanda, Canela, Bergamota",
    notas_corazon: "Azahar, Lirio del valle",
    notas_base:    "Vainilla, Haba tonka, Ámbar, Pachulí",
  },
  {
    slug:   "9-pm-elixir",
    name:   "9 PM ELIXIR",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Intenso",
    promo:  "",
    price:  "105,000.00",
    foto:   "",
    notas_salida:  "Nuez Moscada, Cardamomo, Elemí",
    notas_corazon: "Canela, Cuero, Lavanda",
    notas_base:    "Pachulí, Vainilla, Ládano",
  },
  {
    slug:   "9-pm",
    name:   "9 PM",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9PM.webp",
    notas_salida:  "Manzana, Canela, Lavanda, Bergamota",
    notas_corazon: "Azahar, Lirio del valle",
    notas_base:    "Vainilla, Haba tonka, Ámbar, Pachulí",
  },
  {
    slug:   "9am-dive",
    name:   "9AM Dive",
    cat:    "Unisex, Hombre",
    marca:  "Afnan",
    perfil: "Fresco",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9AM DIVE.webp",
    notas_salida:  "Limón, Pimienta Roja, Menta",
    notas_corazon: "Manzana, Incienso, Cedro",
    notas_base:    "Almizcle, Lirio, Pachulí",
  },
  {
    slug:   "9-am",
    name:   "9 AM",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/9_AM_1.webp",
    notas_salida:  "Limón, Mandarina, Cardamomo, Pimienta rosa",
    notas_corazon: "Lavanda, Azahar, Manzana verde, Rosa",
    notas_base:    "Almizcle, Musgo, Cedro, Pachulí",
  },
  {
    slug:   "club-de-nuit-untold1",
    name:   "Club de Nuit Untold",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Dulce",
    promo:  "100,000.00",
    price:  "105,000.00",
    foto:   "",
    notas_salida:  "Jengibre, Lavanda, Cardamomo",
    notas_corazon: "Iris, Notas florales, Violeta",
    notas_base:    "Ámbar, Sándalo, Vainilla, Almizcle",
  },
];