// ============================================================
// BASE DE DATOS — ST Scent & Textures (151 perfumes)
//
// CÓMO AGREGAR LA FOTO DE UN PERFUME:
// 1. Abrí Tiendanube -> entrá al producto
// 2. Click derecho en la imagen -> "Copiar dirección de imagen"
// 3. Pegá la URL en el campo foto: "" del perfume que corresponda
//
// Si foto queda vacío (""), aparece el frasco CSS automáticamente.
// ============================================================
const PERFUMES = [
  { // DESTACADO en home
    slug:   "your-touch-intense",
    name:   "YOUR TOUCH INTENSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/YOUR TOUCH INTENSE.jpg",
    notas_salida:  "Bergamota, Pimienta negra, Azafrán",
    notas_corazon: "Oud, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "your-touch-amber",
    name:   "YOUR TOUCH AMBER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Jengibre, Oriental spices, Pepper, Azafrán, Frutilla",
    notas_corazon: "Heliotropo, Iris, Jazmín, Magnolia, Rosa, Ylang-ylang",
    notas_base:    "Ámbar, Benjuí, Cedro, Cistus, Olíbano, Ládano",
  },
  {
    slug:   "yeah-parfum",
    name:   "YEAH PARFUM",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Coriander, Azahar, Pimento, Rosewood",
    notas_corazon: "Carnation, Nardo, Heliotropo, Jazmín, Rosa, Ylang-ylang",
    notas_base:    "Cedro, Civet, Opoponax, Vainilla, Ámbar gris, Benjuí",
  },
  { // DESTACADO en home
    slug:   "yeah-man-edp",
    name:   "YEAH MAN EDP",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Pera",
    notas_corazon: "Amberwood, White amber",
    notas_base:    "Creamy notes, Almizcle, Sándalo, Violet leaf",
  },
  {
    slug:   "yara-tous",
    name:   "YARA TOUS",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA TOUS.jpg",
    notas_salida:  "Douglas fir, Lemon grass, Lime leaf, Winter green",
    notas_corazon: "Azerbaijani rose, Blue lotus, Bulgarian rose, Carnation, Grape pomace, Iris",
    notas_base:    "Cambodian oud, Indonesian sandalwood, Mysore sandalwood, Orris root, Siberian musk, White ambergris",
  },
  {
    slug:   "yara-rosa",
    name:   "YARA ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA ROSA.jpg",
    notas_salida:  "Nashi pear, Grape blossom, Guinea pepper",
    notas_corazon: "Black orchid, Christmas rose, Jazmín, Queen-of-the-night",
    notas_base:    "Cashmere wood, Amyris, Ámbar",
  },
  { // DESTACADO en home
    slug:   "yara-moi",
    name:   "YARA MOI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA MOI.jpg",
    notas_salida:  "Pera, Pimienta rosa, Grosella negra",
    notas_corazon: "Nardo, Jazmín, Almendra",
    notas_base:    "Vainilla, Cashmeran, Pachulí",
  },
  { // DESTACADO en home
    slug:   "yara-elixir",
    name:   "YARA ELIXIR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Frutilla, Grosella negra",
    notas_corazon: "Azahar, Jazmín",
    notas_base:    "Vainilla, Caramelo, Ámbar, Almizcle",
  },
  { // DESTACADO en home
    slug:   "yara-candy",
    name:   "YARA CANDY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Dulce",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/YARA CANDY.jpg",
    notas_salida:  "Mandarina verde, Grosella negra",
    notas_corazon: "Gardenia, Frutilla fizz",
    notas_base:    "Sándalo, Vainilla, Almizcle, Ámbar",
  },
  { // DESTACADO en home
    slug:   "vulcan",
    name:   "VULCAN FEU",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "FRENCH AVENUE",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    notas_salida:  "JENGIBRE, LIMÓN, MANGO, RUIBARBO",
    notas_corazon: "VIOLETA, JAZMÍN, PIMIENTA ROSA, PRALINÉ",
    notas_base:    "MUSGO, ÁMBAR GRIS, HABA TONKA, CEDRO",
  },
  { // DESTACADO en home
    slug:   "vogue-rouge",
    name:   "VOGUE ROUGE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Iris, Jazmín, Aldehydes",
    notas_corazon: "Lily of the valley, Almizcle, Ylang-ylang",
    notas_base:    "Cedro, Haba tonka",
  },
  { // DESTACADO en home
    slug:   "vogue-night",
    name:   "VOGUE NIGHT",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Cardamomo, Frambuesa, Ylang-ylang",
    notas_corazon: "Gardenia, Jazmín, Magnolia, Rosa",
    notas_base:    "Ámbar, Benjuí, Ládano, Almizcle, Pachulí, Sándalo",
  },
  { // DESTACADO en home
    slug:   "vintage-radio",
    name:   "VINTAGE RADIO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/VINTAGE RADIO.jpg",
    notas_salida:  "Rose otto, Pomelo",
    notas_corazon: "Jasminum grandiflorum, Rose absolute",
    notas_base:    "Rosewood, Sándalo",
  },
  {
    slug:   "turathi-electric",
    name:   "TURATHI ELECTRIC",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Grosella negra, Notas cítricas, Red apple, Frutilla",
    notas_corazon: "Jazmín, Rosa, Sweet pea, White freesia",
    notas_base:    "Ámbar, Almizcle, Frambuesa, Sándalo",
  },
  { // DESTACADO en home
    slug:   "turathi-blue",
    name:   "TURATHI BLUE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/TURATHI BLUE.jpg",
    notas_salida:  "Aniseed, Bergamota, Pimienta rosa",
    notas_corazon: "Immortelle absolute, Mirra, Opoponax",
    notas_base:    "Vainilla, Styrax, Glycyrrhiza glabra",
  },
  {
    slug:   "toro",
    name:   "TORO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pomelo, Naranja",
    notas_corazon: "Lily of the valley, Linden tree, Red fruits, Rosa",
    notas_base:    "Cedro, Almizcle blanco, Cardamomo, Canela",
  },
  { // DESTACADO en home
    slug:   "teriaq-intense",
    name:   "TERIAQ INTENSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/TERIAQ INTENSE.jpg",
    notas_salida:  "Naranja, Jengibre, Walnut",
    notas_corazon: "Canela, Biscuit, Café",
    notas_base:    "Miel, Vainilla",
  },
  { // DESTACADO en home
    slug:   "shaheen-gold",
    name:   "SHAHEEN GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/SHAHEEN GOLD.jpg",
    notas_salida:  "Bergamota, Pimienta rosa, Azafrán",
    notas_corazon: "Rosa, Jazmín, Iris",
    notas_base:    "Oud, Ámbar, Almizcle, Sándalo",
  },
  {
    slug:   "set-yara-mini",
    name:   "SET YARA MINI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "89,100.00",
    price:  "99,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-yara",
    name:   "SET YARA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-dia-de-la-madre",
    name:   "SET DIA DE LA MADRE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    perfil: "Versátil",
    promo:  "31,500.00",
    price:  "35,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 2 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "set-asad",
    name:   "SET ASAD",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "",
    esSet:  true,
    setInfo: "Vienen de a 4 — Opción ideal para regalo 🎁",
  },
  {
    slug:   "sehr",
    name:   "SEHR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/SEHR.jpg",
    notas_salida:  "Carnation, Rosa, Brazilian rosewood, Grosella negra, Coriander",
    notas_corazon: "Rosa, Jazmín, Ylang-ylang, Iris, Violet leaf",
    notas_base:    "Almizcle, Sándalo, Yellow narcissus",
  },
  {
    slug:   "sceptre-malachite",
    name:   "SCEPTRE MALACHITE",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/SCEPTRE MALACHITE.jpg",
    notas_salida:  "GROSELLAS NEGRAS, BERGAMOTA",
    notas_corazon: "PIMIENTA ROSA, LAVANDA, ESPECIAS, JAZMÍN",
    notas_base:    "ALMIZCLE, VETIVER, ÁMBAR",
  },
  {
    slug:   "salvo",
    name:   "SALVO",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "BERGAMOTA",
    notas_corazon: "ANÍS ESTRELLADO, LAVANDA, NUEZ MOSCADA",
    notas_base:    "VAINILLA, AMBROXAN",
  },
  {
    slug:   "sakeena",
    name:   "SAKEENA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Pera, Frambuesa, Bergamota",
    notas_corazon: "Rosa, Peonía, Jazmín",
    notas_base:    "Almizcle blanco, Cedro, Ámbar",
  },
  {
    slug:   "rayhaan-tropical-vibe",
    name:   "TROPICAL VIBE RAYHAAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Rayhaan",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "BERGAMOTA, MANGO, ANANÁ",
    notas_corazon: "COCO",
    notas_base:    "VETIVER, SÁNDALO, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "rayhaan-pacific",
    name:   "PACIFIC RAYHAAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Rayhaan",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "CARDAMOMO, NARANJA, LIMÓN, BERGAMOTA",
    notas_corazon: "CIPRÉS, LAVANDA",
    notas_base:    "ÁMBAR",
  },
  {
    slug:   "rave-now-rosa",
    name:   "RAVE NOW ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/RAVE NOW WOMAN.jpg",
    notas_salida:  "Jazmín",
    notas_corazon: "Apricot, Vainilla, Vetiver",
    notas_base:    "Ámbar gris, Almizcle, Sándalo",
  },
  {
    slug:   "ramz-gold",
    name:   "RAMZ GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Azafrán, Pimienta rosa",
    notas_corazon: "Rosa, Jazmín, Oud",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "ramz",
    name:   "RAMZ",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Lavanda",
    notas_corazon: "Geranio, Oak, Haba tonka, Vainilla",
    notas_base:    "Grosella negra, Limón, Mandarina, Pera",
  },
  {
    slug:   "qaed-untamed",
    name:   "QAED UNTAMED",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/QAED AL FURSAN UNTAMED.jpg",
    notas_salida:  "Canela, Cardamomo, Mandarina, Nuez moscada",
    notas_corazon: "Caramelo, Lavanda, Salvia, Geranio, Ciprés",
    notas_base:    "Ámbar, Cedro, Olíbano, Ládano, Vetiver",
  },
  {
    slug:   "qaed-unlimited",
    name:   "QAED UNLIMITED",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "58,500.00",
    price:  "65,000.00",
    foto:   "img/QAED AL FURSAN UNLIMITED.jpg",
    notas_salida:  "Coco, Ananá, Cítricos",
    notas_corazon: "Ylang-ylang, Frangipani, Jazmín",
    notas_base:    "Vainilla, Almizcle, Sándalo, Notas dulces",
  },
  {
    slug:   "qaed-al-fursan",
    name:   "QAED AL FURSAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "58,500.00",
    price:  "65,000.00",
    foto:   "img/QAED AL FURSAN.jpg",
    notas_salida:  "Ananá, Azafrán",
    notas_corazon: "Abeto balsámico, Jazmín",
    notas_base:    "Cedro, Ámbar, Oud",
  },
  {
    slug:   "pistacho",
    name:   "PISTACHO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Anfar",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/PISTACHIO.jpg",
    notas_salida:  "Pistacho, Almendra, Bergamota",
    notas_corazon: "Praliné, Notas gourmand, Rosa",
    notas_base:    "Vainilla, Almizcle blanco, Sándalo",
  },
  {
    slug:   "pisa",
    name:   "PISA",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/PISA.jpg",
    notas_salida:  "BERGAMOTA, LIMÓN, NARANJA",
    notas_corazon: "CEDRO",
    notas_base:    "SÁNDALO, ÁMBAR",
  },
  {
    slug:   "philos-rosso",
    name:   "PHILOS ROSSO",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/PHILOS ROSSO.jpg",
    notas_salida:  "FRAMBUESA, LIMÓN",
    notas_corazon: "ROSA, JAZMÍN",
    notas_base:    "VAINILLA, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "philos-pura",
    name:   "PHILOS PURA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/PHILOS PURA.jpg",
    notas_salida:  "LIMÓN, NARANJA, BERGAMOTA",
    notas_corazon: "FRUTAS",
    notas_base:    "ALMIZCLE, VAINILLA, ÁMBAR",
  },
  {
    slug:   "perseus-exclusif",
    name:   "PERSEUS EXCLUSIF",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Pimienta negra, Manzana verde",
    notas_corazon: "Abedul, Pachulí, Jazmín, Rosa",
    notas_base:    "Almizcle, Ámbar gris, Cedro, Vainilla",
  },
  {
    slug:   "perseus",
    name:   "PERSEUS",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Blueberry",
    notas_corazon: "Nardo",
    notas_base:    "Ámbar, Ládano",
  },
  {
    slug:   "opera-rouge",
    name:   "OPERA ROUGE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pomelo, Limón, Pimienta rosa",
    notas_corazon: "Jengibre, Jazmín, Nuez moscada",
    notas_base:    "Cedro, Olíbano, Pachulí, Sándalo, Vetiver, Almizcle blanco",
  },
  {
    slug:   "odyssey-revolution",
    name:   "ODYSSEY REVOLUTION",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Cardamom absolute, Azafrán",
    notas_corazon: "Hyacinth, Karmaflor®, Petalia®",
    notas_base:    "Cedro, Immortelle absolute, Almizcle, Vainilla",
  },
  {
    slug:   "odyssey-bahamas",
    name:   "ODYSSEY BAHAMAS",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "MELÓN, ALGAS, SAL, CIRUELA, PERA",
    notas_corazon: "MUSGO, INCIENSO, NOTAS ACUÁTICAS",
    notas_base:    "AZÚCAR, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "odissey-tyrant",
    name:   "ODISSEY TYRANT",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "POMELO",
    notas_corazon: "PIMIENTA, GERANIO, LAVANDA, ELEMÍ",
    notas_base:    "CEDRO, VETIVER, AMBROXAN",
  },
  {
    slug:   "odissey-mega",
    name:   "ODISSEY MEGA MAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "MENTA, BERGAMOTA, NARANJA, JENGIBRE",
    notas_corazon: "ENEBRO, GERANIO, ANANÁ",
    notas_base:    "CEDRO, ALMIZCLE, VETIVER, HABA TONKA",
  },
  {
    slug:   "odissey-mandarin",
    name:   "ODISSEY MANDARIN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/ODYSSEY MANDARIN SKY.jpg",
    notas_salida:  "Bergamota, Maracuyá, Coriander",
    notas_corazon: "Honeysuckle, Violeta, Mimosa",
    notas_base:    "Ambrette, Almizcle, Vetiver",
  },
  {
    slug:   "odissey-limoni",
    name:   "ODISSEY LIMONI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY LIMONI.jpg",
    notas_salida:  "Bergamota, Notas verdes, Spices",
    notas_corazon: "Ámbar, Jazmín, Musgo",
    notas_base:    "Ámbar, Pachulí, Woods",
  },
  {
    slug:   "odissey-homme-white",
    name:   "ODISSEY HOMME WHITE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY HOMME.jpg",
    notas_salida:  "PIMIENTA ROSA, POMELO",
    notas_corazon: "HOJAS DE VIOLETA, NOTAS MARINAS",
    notas_base:    "AMBERWOOD, MADERA, ÁMBAR",
  },
  {
    slug:   "odissey-homme-negro",
    name:   "ODISSEY HOMME EDP",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY HOMME.jpg",
    notas_salida:  "VAINILLA, ÁMBAR",
    notas_corazon: "ESPECIAS, IRIS",
    notas_base:    "CUERO, VAINILLA, JAZMÍN",
  },
  {
    slug:   "odissey-candee",
    name:   "ODISSEY CANDEE",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "FRUTILLA, DURAZNO, BERGAMOTA, FRAMBUESA, GERANIO",
    notas_corazon: "CARAMELO, MARACUYÁ, JAZMÍN",
    notas_base:    "ALMIZCLE, PACHULÍ, ÁMBAR",
  },
  {
    slug:   "odissey-aqua",
    name:   "ODISSEY AQUA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Fresco",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ODYSSEY AQUA.jpg",
    notas_salida:  "Tangerina, Bergamota, Chamomile, Olíbano",
    notas_corazon: "Mirra, Ámbar, Orquídea",
    notas_base:    "Sumatran benzoin, Bourbon vanilla, Styrax, Orris butter, Vetiver",
  },
  {
    slug:   "odissey-aoud",
    name:   "ODISSEY AOUD",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Intenso",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "AZAFRÁN, NUEZ MOSCADA, LAVANDA",
    notas_corazon: "MADERA DE OUD",
    notas_base:    "AMBROXAN, PACHULÍ, ALMIZCLE",
  },
  {
    slug:   "nebula-ii",
    name:   "NEBULA II",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Limón",
    notas_corazon: "Jazmín, Lirio, Lotus, Rosa",
    notas_base:    "Ámbar, Almizcle, Sándalo, Woods",
  },
  {
    slug:   "nebula-i",
    name:   "NEBULA I",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Limón, Pimienta negra",
    notas_corazon: "Iris, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Cedro",
  },
  {
    slug:   "nebras",
    name:   "NEBRAS",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/NEBRAS.jpg",
    notas_salida:  "BAYAS ROJAS, MANDARINA",
    notas_corazon: "VAINILLA, CACAO, ROSA",
    notas_base:    "ÁMBAR, AZÚCAR, ALMIZCLE, HABA TONKA",
  },
  {
    slug:   "miss-chic",
    name:   "MISS CHIC",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "Mandarina, Aldehydes, Neroli, Naranja",
    notas_corazon: "Haba tonka, Almizcle blanco, Pimienta negra, Almendra",
    notas_base:    "Bálsamo, Cedro, Vetiver",
  },
  {
    slug:   "mayar-natural",
    name:   "MAYAR NATURAL",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR NATURAL.jpg",
    notas_salida:  "Pomelo, Durazno, Bergamota, Naranja",
    notas_corazon: "Jazmín, Geranio, Rosa, Lychee",
    notas_base:    "Almizcle, Vainilla, Vetiver, Pachulí",
  },
  {
    slug:   "mayar-cherry",
    name:   "MAYAR CHERRY",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR CHERRY.jpg",
    notas_salida:  "Cereza, Almendra, Bergamota",
    notas_corazon: "Rosa turca, Jazmín, Heliotropo",
    notas_base:    "Vainilla, Almizcle, Sándalo, Ámbar",
  },
  {
    slug:   "mayar",
    name:   "MAYAR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/MAYAR.jpg",
    notas_salida:  "Mandarina, Bergamota, Durazno",
    notas_corazon: "Jazmín, Rosa, Notas florales",
    notas_base:    "Vainilla, Almizcle, Sándalo, Pachulí",
  },
  {
    slug:   "malik-al-tayoor",
    name:   "MALIK AL TAYOOR CONCENTRATED",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "BERGAMOTA, ANANÁ, MANZANA",
    notas_corazon: "HOJAS DE VIOLETA",
    notas_base:    "LÁDANO, CACHEMIRA",
  },
  {
    slug:   "luxe-emerald",
    name:   "LUXE EMERALD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "DURAZNO, LITCHI, GROSELLAS NEGRAS",
    notas_corazon: "PEONÍA, JAZMÍN, MANZANA VERDE",
    notas_base:    "PRALINÉ, AMBROXAN, MUSGO, ALMIZCLE, VAINILLA",
  },
  {
    slug:   "luxe",
    name:   "LUXE STREET",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "",
    notas_salida:  "CILANTRO, BERGAMOTA",
    notas_corazon: "MANZANA, VAINILLA, AMBROXAN",
    notas_base:    "ÁMBAR GRIS, HABA TONKA, MADERA",
  },
  {
    slug:   "liquid-brun",
    name:   "LIQUID BRUN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/LIQUID BRUN.jpg",
    notas_salida:  "Bergamota, Lavanda, Limón",
    notas_corazon: "Cedro, Olive blossom",
    notas_base:    "Ámbar, Almizcle, Haba tonka, Vainilla",
  },
  {
    slug:   "leonie",
    name:   "LÉONIE",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "LAVANDA, MANDARINA, GROSELLAS NEGRAS",
    notas_corazon: "JAZMÍN, FLOR DEL NARANJO",
    notas_base:    "CEDRO, ALMIZCLE, ÁMBAR GRIS, VAINILLA",
  },
  {
    slug:   "la-voie",
    name:   "LA VOIE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Pimienta rosa, Frambuesa",
    notas_corazon: "Rosa, Iris, Jazmín",
    notas_base:    "Pachulí, Almizcle, Vainilla, Cedro",
  },
  {
    slug:   "la-vivacite",
    name:   "LA VIVACITÉ",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/LA VIVACITÉ.jpg",
    notas_salida:  "PERA, GROSELLA NEGRA",
    notas_corazon: "IRIS, FLOR DEL NARANJO, JAZMÍN",
    notas_base:    "PRALINÉ, VAINILLA, PACHULÍ, HABA TONKA",
  },
  {
    slug:   "kingdom-women",
    name:   "THE KINGDOM WOMEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/THE_KINGDOM_WOMEN.jpg",
    notas_salida:  "PERA, PEONÍA",
    notas_corazon: "JAZMÍN, PRALINÉ, HABA TONKA",
    notas_base:    "SÁNDALO, ALMIZCLE, ÁMBAR, VAINILLA",
  },
  {
    slug:   "kingdom-man",
    name:   "THE KINGDOM MEN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/THE KINGDOM MAN.jpg",
    notas_salida:  "MENTA, LAVANDA",
    notas_corazon: "VAINILLA, TABACO, FLOR DEL NARANJO",
    notas_base:    "BENJUÍ, HABA TONKA",
  },
  {
    slug:   "khanjar",
    name:   "KHANJAR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "112,500.00",
    price:  "125,000.00",
    foto:   "img/KHANJAR.jpg",
    notas_salida:  "Manzana verde, Notas acuáticas, Bergamota, Cardamomo",
    notas_corazon: "Cyclamen, Jazmín, Lily of the valley, Vetiver",
    notas_base:    "Ámbar, Cedro, Crystal musk, Musgo de roble",
  },
  {
    slug:   "khamrah-qawa",
    name:   "KHAMRAH QAWA",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH QAHWA.jpg",
    notas_salida:  "Canela, Cardamomo, Jengibre",
    notas_corazon: "Praliné, Frutas confitadas, Flores blancas",
    notas_base:    "Café, Vainilla, Haba tonka, Benjuí, Almizcle",
  },
  {
    slug:   "khamrah-dukhan",
    name:   "KHAMRAH DUKHAN",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH DUKHAN.jpg",
    notas_salida:  "Mandarina, Pimentón, Especias ahumadas",
    notas_corazon: "Labdanum, Azahar, Incienso, Pachulí",
    notas_base:    "Tabaco, Ámbar, Haba tonka, Benjuí, Praliné",
  },
  {
    slug:   "khamrah",
    name:   "KHAMRAH",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Dulce",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/KHAMRAH.jpg",
    notas_salida:  "Bergamota, Canela",
    notas_corazon: "Flores blancas, Madera de caoba",
    notas_base:    "Vainilla, Ámbar, Benjuí, Mirra",
  },
  {
    slug:   "jorge-di-profumo-aqua",
    name:   "JORGE DI PROFUMO AQUA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Fresco",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Manzana verde, Notas acuáticas, Bergamota",
    notas_corazon: "Ciclamen, Jazmín, Lirio del valle",
    notas_base:    "Ámbar, Cedro, Almizcle, Musgo de roble",
  },
  {
    slug:   "jorge-di-profumo",
    name:   "JORGE DI PROFUMO",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Grosella negra",
    notas_corazon: "Rosa, Jazmín, Pachulí",
    notas_base:    "Almizcle, Ámbar, Cedro, Musgo de roble",
  },
  {
    slug:   "jean-lowe-inmortal",
    name:   "JEAN LOWE INMORTAL",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/JEAN LOWE IMMORTEL.jpg",
    notas_salida:  "Bergamota, Lavanda, Pimienta negra",
    notas_corazon: "Iris, Violeta, Geranio",
    notas_base:    "Ámbar gris, Cedro, Almizcle",
  },
  {
    slug:   "ishq-al-shuyuk-gold",
    name:   "ISHQ AL SHUYUK GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/ISHQ AL SHUYUK GOLD.jpg",
    notas_salida:  "CARAMELO, AZAFRÁN",
    notas_corazon: "GAMUZA, CUERO, HABA TONKA",
    notas_base:    "ÁMBAR, VAINILLA, ALMIZCLE",
  },
  {
    slug:   "ishq-al-shuyuk",
    name:   "ISHQ AL SHUYUK",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "",
    notas_salida:  "Calabrian bergamot, Carrot seed, Mandarina, Azahar, Pimienta rosa",
    notas_corazon: "Orris root, Osmanthus, Ylang-ylang, Egyptian jasmine, Star anise, Nardo",
    notas_base:    "Iris, Ceylonese sandalwood, Cashmere, Cedro, Haba tonka, Vetiver",
  },
  {
    slug:   "historic-olmeda",
    name:   "HISTORIC OLMEDA",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "AFNAN",
    perfil: "Versátil",
    promo:  "79,200.00",
    price:  "88,000.00",
    foto:   "",
    notas_salida:  "POMELO, CARDAMOMO, ENEBRO, PIMIENTA ROSA",
    notas_corazon: "BERGAMOTA, CEDRO, NUEZ MOSCADA, JAZMÍN",
    notas_base:    "ALMIZCLE, ÁMBAR GRIS, MANZANA, PACHULÍ",
  },
  {
    slug:   "his-confession",
    name:   "HIS CONFESSION",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/HIS CONFESSION.jpg",
    notas_salida:  "LAVANDA, MANDARINA, CANELA",
    notas_corazon: "IRIS, BENJUÍ, CIPRÉS",
    notas_base:    "ÁMBAR, INCIENSO, HABA TONKA, VAINILLA, PACHULÍ",
  },
  {
    slug:   "her-confession",
    name:   "HER CONFESSION",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/HER CONFESSION.jpg",
    notas_salida:  "CANELA",
    notas_corazon: "JAZMÍN, INCIENSO, NARDO",
    notas_base:    "ALMIZCLE, VAINILLA, HABA TONKA",
  },
  {
    slug:   "hayaati-rosa",
    name:   "HAYAATI ROSA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Frambuesa, Rosa, Bergamota",
    notas_corazon: "Peonía, Jazmín, Notas florales",
    notas_base:    "Vainilla, Almizcle blanco, Sándalo",
  },
  {
    slug:   "hayaati-al-maleky",
    name:   "HAYAATI AL MALEKY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Manzana, Bergamota, Pimienta rosa",
    notas_corazon: "Iris, Rosa, Notas amaderadas",
    notas_base:    "Vainilla, Ámbar, Almizcle, Cedro",
  },
  {
    slug:   "hayaati",
    name:   "HAYAATI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "img/HAYAATI.jpg",
    notas_salida:  "Nuez moscada, Pimienta rosa, Jengibre, Bergamota",
    notas_corazon: "Incienso, Cedro, Ládano, Notas amaderadas",
    notas_base:    "Ámbar, Almizcle, Ámbar gris",
  },
  {
    slug:   "haya",
    name:   "HAYA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/LATAFFA_HAYA.jpg",
    notas_salida:  "Canela, Tabaco, Pimienta negra",
    notas_corazon: "Ládano, Nuez moscada, Tonka bean absolute",
    notas_base:    "Vainilla, Vetiver, Papyrus",
  },
  {
    slug:   "hawas-ice",
    name:   "HAWAS ICE",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Fresco",
    promo:  "98,100.00",
    price:  "109,000.00",
    foto:   "img/HAWAS ICE.jpg",
    notas_salida:  "Bergamota, Menta, Manzana verde",
    notas_corazon: "Ambroxan, Geranio, Notas acuáticas",
    notas_base:    "Almizcle, Sándalo, Notas amaderadas",
  },
  {
    slug:   "hawas-fire",
    name:   "HAWAS FIRE",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Pimienta rosa, Canela",
    notas_corazon: "Olíbano, Rosa, Pachulí",
    notas_base:    "Vainilla, Ámbar, Almizcle, Oud",
  },
  {
    slug:   "hawas-eclat",
    name:   "HAWAS ECLAT",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "85,050.00",
    price:  "94,500.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Notas acuáticas",
    notas_corazon: "Jazmín, Rosa, Geranio",
    notas_base:    "Almizcle, Cedro, Ámbar",
  },
  {
    slug:   "hawas",
    name:   "HAWAS",
    cat:    "Unisex",
    marca:  "Rasasi",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/HAWAS.jpg",
    notas_salida:  "Cypress, Lavanda, Pine, Violet leaf absolute, West Indian lantana",
    notas_corazon: "Callitris columellaris, Civet, Clary sage, Green tea, Iris, White oud",
    notas_base:    "Australian sandalwood, Castoreum, Indian deer musk, Iris, Thai oud",
  },
  {
    slug:   "glacier-ultra",
    name:   "GLACIER ULTRA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "img/GLACIER ULTRA.jpg",
    notas_salida:  "Bergamota, Pomelo, Pimienta rosa",
    notas_corazon: "Geranio, Lavanda, Salvia",
    notas_base:    "Cedro, Almizcle, Ambroxan",
  },
  {
    slug:   "glacier-le-noir",
    name:   "GLACIER LE NOIR",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Intenso",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pimienta negra, Bergamota, Cardamomo",
    notas_corazon: "Iris, Violeta, Incienso",
    notas_base:    "Cedro, Ámbar, Almizcle, Cuero",
  },
  {
    slug:   "glacier-bold",
    name:   "GLACIER BOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Pimienta negra, Elemi resin, Rosa",
    notas_corazon: "Ládano, Azafrán, Violeta",
    notas_base:    "Ámbar, Oud, Sándalo, Almizcle blanco",
  },
  {
    slug:   "glacier-bella",
    name:   "GLACIER BELLA",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Bergamota, Mandarina, Grosella negra",
    notas_corazon: "Jazmín, Rosa, Notas florales",
    notas_base:    "Almizcle blanco, Cedro, Ámbar",
  },
  {
    slug:   "ghost-spectre",
    name:   "GHOST SPECTRE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "French Avenue",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/GHOST SPECTRE.jpg",
    notas_salida:  "JENGIBRE, BERGAMOTA, CARDAMOMO",
    notas_corazon: "ROSA, PIMIENTA ROSA",
    notas_base:    "CEDRO, PACHULÍ, VAINILLA",
  },
  {
    slug:   "gharam",
    name:   "GHARAM",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "",
    notas_salida:  "Bitter orange, Damson plum, Higo",
    notas_corazon: "Cocoa, Jazmín, Turkish rose, Ylang-ylang",
    notas_base:    "Ambrette, Oud, Pachulí, Sándalo, Vainilla",
  },
  {
    slug:   "galactic-marron",
    name:   "GALACTIC MEN INTENSE",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "",
    notas_salida:  "MIEL, TABACO",
    notas_corazon: "VAINILLA, CACAO, PACHULÍ",
    notas_base:    "SÁNDALO, ÁMBAR",
  },
  {
    slug:   "fhakar-women",
    name:   "FHAKAR WOMEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR ROSE.jpg",
    notas_salida:  "Rosa, Bergamota, Frambuesa",
    notas_corazon: "Jazmín, Peonía, Notas florales",
    notas_base:    "Almizcle, Vainilla, Pachulí, Sándalo",
  },
  {
    slug:   "fhakar-man",
    name:   "FHAKAR MAN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR.jpg",
    notas_salida:  "Pomelo, Durazno, Bergamota, Naranja",
    notas_corazon: "Jazmín, Geranio, Rosa, Lychee",
    notas_base:    "Almizcle, Vainilla, Vetiver, Pachulí",
  },
  {
    slug:   "fhakar-gold",
    name:   "FHAKAR GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "76,500.00",
    price:  "85,000.00",
    foto:   "img/FAKHAR EXTRAIT GOLD.jpg",
    notas_salida:  "Bergamota, Pomelo, Pimienta rosa",
    notas_corazon: "Rosa, Jazmín, Geranio",
    notas_base:    "Pachulí, Almizcle, Vainilla, Vetiver",
  },
  {
    slug:   "fakhar-platin",
    name:   "FAKHAR PLATIN",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/FAKHAR PLATIN.jpg",
    notas_salida:  "Pomelo, Petitgrain",
    notas_corazon: "Blue lotus absolute, Labdanum absolute, Melon",
    notas_base:    "Camphor, Laurel, Pachulí",
  },
  {
    slug:   "extravagant-lover",
    name:   "EXTRAVAGANT LOVER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "Red mandarin orange, Peppermint",
    notas_corazon: "Rosa, Canela",
    notas_base:    "Ámbar, Cuero",
  },
  {
    slug:   "emeer",
    name:   "EMEER",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/EMEER.jpg",
    notas_salida:  "Calabrian bergamot, Cardamomo, Pomelo",
    notas_corazon: "Cypriol, Olíbano",
    notas_base:    "Amberwood, Haitian vetiver, Virginia cedar",
  },
  {
    slug:   "emaan",
    name:   "EMAAN",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/EMAAN.jpg",
    notas_salida:  "Pink freesia, Magnolia, Lavanda",
    notas_corazon: "Rosa centifolia, Almizcle",
    notas_base:    "Ambroxan, Orris butter, Cashmere wood",
  },
  {
    slug:   "eclaire-banoffi",
    name:   "ECLAIRE BANOFFI",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "85,050.00",
    price:  "94,500.00",
    foto:   "",
    notas_salida:  "Banana, Caramelo, Bergamota",
    notas_corazon: "Praliné, Café, Notas gourmand",
    notas_base:    "Vainilla, Haba tonka, Almizcle",
  },
  {
    slug:   "eclaire",
    name:   "ECLAIRE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "img/ECLAIRE.jpg",
    notas_salida:  "Pomelo, Bergamota, Frambuesa",
    notas_corazon: "Rosa, Jazmín, Notas florales",
    notas_base:    "Vainilla, Almizcle, Pachulí, Ámbar",
  },
  {
    slug:   "desirable-addiction",
    name:   "DESIRABLE ADDICTION",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "61,200.00",
    price:  "68,000.00",
    foto:   "",
    notas_salida:  "LIMÓN",
    notas_corazon: "RON, FLOR DEL NARANJO",
    notas_base:    "VAINILLA",
  },
  {
    slug:   "delilah",
    name:   "DELILAH",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/MAISONALHAMBRA-DELILAH.jpg",
    notas_salida:  "Pimienta negra, Elemi resin, Olíbano, Oud",
    notas_corazon: "Benjuí, Azafrán, Vanilla blossom",
    notas_base:    "Cedro, Kashmiri musk, Smoked vanilla",
  },
  {
    slug:   "confidential-platin",
    name:   "CONFIDENTIAL PLATIN",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "",
    notas_salida:  "PIMIENTA, CIPRÉS, BERGAMOTA",
    notas_corazon: "NOTAS MARINAS, INCIENSO",
    notas_base:    "ALMIZCLE, MUSGO, LÁDANO, ÁMBAR GRIS",
  },
  {
    slug:   "confidential-gold",
    name:   "CONFIDENTIAL GOLD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/CONFIDENTIAL GOLD.jpg",
    notas_salida:  "Petitgrain",
    notas_corazon: "Lily of the valley",
    notas_base:    "Pachulí",
  },
  {
    slug:   "checkmate-queen",
    name:   "QUEEN",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "ARMAF",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "NOTAS VERDES",
    notas_corazon: "ESPECIAS, HIGO",
    notas_base:    "SÁNDALO",
  },
  {
    slug:   "cdn-urban-elixir",
    name:   "CDN URBAN ELIXIR",
    cat:    "Hombre",
    marca:  "Armaf",
    perfil: "Intenso",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/CDN URBAN MAN ELIXIR.jpg",
    notas_salida:  "BERGAMOTA, PIMIENTA ROSA, JAZMÍN, FLOR DEL NARANJO",
    notas_corazon: "LAVANDA, VETIVER, GERANIO, AZAFRÁN",
    notas_base:    "ÁMBAR, LÁDANO, PACHULÍ, AMBROXAN",
  },
  {
    slug:   "cdn-untold",
    name:   "CDN UNTOLD",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "94,500.00",
    price:  "105,000.00",
    foto:   "img/ARMAF-CDN_UNTOLD.jpg",
    notas_salida:  "AZAFRÁN, JAZMÍN",
    notas_corazon: "ÁMBAR GRIS, AMBERWOOD",
    notas_base:    "CEDRO",
  },
  {
    slug:   "cdn-sillage",
    name:   "CDN SILLAGE",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Fresco",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_SILLAGE.jpg",
    notas_salida:  "Bitter orange blossom, Calabrian bergamot",
    notas_corazon: "Azafrán, Orris root, Canela, Nuez moscada, Jazmín, Dried fruits",
    notas_base:    "Ládano, Oud, Ámbar, Benjuí, Pachulí, Vainilla",
  },
  {
    slug:   "cdn-rosa",
    name:   "CDN ROSA",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Manzana verde, Notas acuáticas, Bergamota, Cardamomo",
    notas_corazon: "Cyclamen, Jazmín, Lily of the valley, Vetiver",
    notas_base:    "Ámbar, Cedro, Crystal musk, Musgo de roble",
  },
  {
    slug:   "cdn-precieux",
    name:   "CDN PRECIEUX",
    cat:    "Unisex, Hombre",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "112,500.00",
    price:  "125,000.00",
    foto:   "img/ARMAF-CDN_PRECIEUX.jpg",
    notas_salida:  "CARAMELO, PERA, PIMIENTA , ANANÁ, LIMÓN, BERGAMOTA",
    notas_corazon: "MUSGO, ANÍS, MADERA, JAZMÍN",
    notas_base:    "AMBROXAN, ALMIZCLE, PACHULÍ, CUERO, VAINILLA",
  },
  {
    slug:   "cdn-milestone",
    name:   "CDN MILESTONE",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Ananá, Bergamota, Manzana verde",
    notas_corazon: "Abedul, Pachulí, Rosa, Jazmín",
    notas_base:    "Almizcle, Vainilla, Cedro, Ámbar",
  },
  {
    slug:   "cdn-maleka",
    name:   "CDN MALEKA",
    cat:    "Mujer",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_MALEKA.jpg",
    notas_salida:  "PIMIENTA ROSA, LITCHI, BERGAMOTA",
    notas_corazon: "LIRIO",
    notas_base:    "AMBROXAN, PRALINÉ, SÁNDALO",
  },
  {
    slug:   "cdn-lionheart-women",
    name:   "CDN LIONHEART WOMEN",
    cat:    "Mujer",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "VAINILLA, LAVANDA",
    notas_corazon: "CACAO, JENGIBRE",
    notas_base:    "VAINILLA",
  },
  {
    slug:   "cdn-iconic",
    name:   "CDN ICONIC",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "89,550.00",
    price:  "99,500.00",
    foto:   "img/ARMAF-CDN_ICONIC.jpg",
    notas_salida:  "Woodland strawberry, Sandía, Bergamota",
    notas_corazon: "Lily of the valley, Star jasmine",
    notas_base:    "Vanilla cream, Cedro, Almizcle",
  },
  {
    slug:   "club-de-nuit",
    name:   "Club de Nuit",
    cat:    "Unisex",
    marca:  "Armaf",
    perfil: "Versátil",
    promo:  "85,500.00",
    price:  "95,000.00",
    foto:   "",
    notas_salida:  "Limón, Pimienta negra, Menta",
    notas_corazon: "Rosa, Jazmín, Abedul",
    notas_base:    "Almizcle, Ámbar, Pachulí, Cedro",
  },
  {
    slug:   "caprice",
    name:   "AL NASHAMA CAPRICE",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Fresco",
    promo:  "67,500.00",
    price:  "75,000.00",
    foto:   "img/AL NASHAMA CAPRICE.jpg",
    notas_salida:  "JENGIBRE, CARDAMOMO, BERGAMOTA, LIMÓN",
    notas_corazon: "LAVANDA, GERANIO, MENTA",
    notas_base:    "ÁMBAR, PACHULÍ",
  },
  {
    slug:   "candid",
    name:   "CANDID",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "71,100.00",
    price:  "79,000.00",
    foto:   "img/MAISONALHAMBRA_CANDID.jpg",
    notas_salida:  "BERGAMOTA, ANANÁ",
    notas_corazon: "JAZMÍN, ROSA, FLOR DEL NARANJO",
    notas_base:    "VAINILLA, PACHULÍ, HABA TONKA",
  },
  {
    slug:   "cherry-bouquet",
    name:   "CHERRY BOUQUET",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Afnan",
    perfil: "Dulce",
    promo:  "80,100.00",
    price:  "89,000.00",
    foto:   "img/AFNAN-CHERRY_BOUQUET.jpg",
    notas_salida:  "Cereza negra, Licor de cereza, Cereza ácida, Almendra",
    notas_corazon: "Ciruela, Frambuesa, Rosa de Damasco, Jazmín Sambac",
    notas_base:    "Vainilla, Vetiver, Clavo, Cedro, Pachulí",
  },
  {
    slug:   "bharara-king",
    name:   "BHARARA KING",
    cat:    "Hombre",
    marca:  "ST Perfumería",
    marca_real: "Bharara",
    perfil: "Versátil",
    promo:  "125,100.00",
    price:  "139,000.00",
    foto:   "img/BHARARA KING.jpg",
    notas_salida:  "Bergamota, Ananá, Pimienta negra",
    notas_corazon: "Azafrán, Rosa, Jazmín",
    notas_base:    "Oud, Ámbar, Vainilla, Almizcle",
  },
  {
    slug:   "bharara-chocolate",
    name:   "BHARARA CHOCOLATE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Bharara",
    perfil: "Dulce",
    promo:  "125,100.00",
    price:  "139,000.00",
    foto:   "img/BHARARA CHOCOLATE.jpg",
    notas_salida:  "Bergamota, Violeta, Notas cítricas, Mandarina",
    notas_corazon: "Rosebud, Gardenia, Jasmine sambac, Iris",
    notas_base:    "Vainilla, Balsamic notes, Cedro, Sándalo",
  },
  {
    slug:   "badee-sublime",
    name:   "BADEE SUBLIME",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE_SUBLIME_1.jpg",
    notas_salida:  "LITCHI, ROSA, MANZANA",
    notas_corazon: "CIRUELA, JAZMÍN",
    notas_base:    "PACHULÍ, VAINILLA, VETIVER",
  },
  {
    slug:   "badee-oud-for-glory",
    name:   "BADEE OUD FOR GLORY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE OUD FOR GLORY.jpg",
    notas_salida:  "Ananá, Calabrian bergamot",
    notas_corazon: "Egyptian geranium, Magnolia",
    notas_base:    "Praliné, Indonesian patchouli, Vetiver, Cedro",
  },
  {
    slug:   "badee-noble-blush",
    name:   "BADEE NOBLE BLUSH",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE NOBLE BLUSH.jpg",
    notas_salida:  "LECHE",
    notas_corazon: "MERENGUE, ALMENDRA",
    notas_base:    "ALMIZCLE, SÁNDALO, VAINILLA",
  },
  {
    slug:   "badee-honor-y-gloria",
    name:   "BADEE HONOR AND GLORY",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE HONOR Y GLORY.jpg",
    notas_salida:  "ANANÁ",
    notas_corazon: "CANELA, CÚRCUMA, PIMIENTA",
    notas_base:    "VAINILLA, MUSGO, SÁNDALO, CACHEMIRA",
  },
  {
    slug:   "badee-amethyst",
    name:   "BADEE AMETHYST",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/BADEE_AMETHYST_1.jpg",
    notas_salida:  "PIMIENTA ROSA, BERGAMOTA",
    notas_corazon: "ROSA, JAZMÍN",
    notas_base:    "OUD, VAINILLA, ÁMBAR",
  },
  {
    slug:   "atlas",
    name:   "ATLAS",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "88,650.00",
    price:  "98,500.00",
    foto:   "",
    notas_salida:  "SAL, LIMÓN",
    notas_corazon: "DAVANA, IRIS",
    notas_base:    "ÁMBAR GRIS, SÁNDALO, MUSGO",
  },
  {
    slug:   "asad-elixir",
    name:   "ASAD ELIXIR",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "99,500.00",
    foto:   "",
    notas_salida:  "Pimienta negra, Cítricos, Limón, Menta",
    notas_corazon: "Canela, Clavo, Jengibre",
    notas_base:    "Amberwood, Madera de guayaco, Cuero",
  },
  {
    slug:   "asad-bourbon",
    name:   "ASAD BOURBON",
    cat:    "Hombre",
    marca:  "Lattafa",
    perfil: "Intenso",
    promo:  "",
    price:  "98,500.00",
    foto:   "img/ASAD BOURBON.jpg",
    notas_salida:  "Pimienta rosa, Lavanda, Ciruela",
    notas_corazon: "Cacao, Nuez moscada, Davana",
    notas_base:    "Vetiver, Vainilla bourbon, Ámbar",
  },
  {
    slug:   "asad",
    name:   "ASAD",
    cat:    "Unisex",
    marca:  "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ASAD.jpg",
    notas_salida:  "Pimienta negra, Ananá, Tabaco",
    notas_corazon: "Café, Pachulí, Iris",
    notas_base:    "Ámbar, Vainilla, Maderas secas, Benjuí, Ládano",
  },
  {
    slug:   "art-of-universe",
    name:   "ART OF UNIVERSE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Maison Alhambra",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ART OF UNIVERSE.jpg",
    notas_salida:  "Cardamomo, Jengibre, Osmanthus",
    notas_corazon: "Hyacinth, Iris, Lirio, Naranja, Rosa",
    notas_base:    "Nardo, Cedro, Solar note, Vainilla",
  },
  {
    slug:   "art-of-nature-i",
    name:   "ART OF NATURE I",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/ART OF NATURE I.jpg",
    notas_salida:  "HIGO, CIRUELA",
    notas_corazon: "CUERO, RUIBARBO, ROSA",
    notas_base:    "OUD, ÁMAR GRIS, VAINILLA",
  },
  {
    slug:   "antique",
    name:   "ANTIQUE",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ANTIQUE.jpg",
    notas_salida:  "HIGO,CARDAMOMO, LECHE, COCO",
    notas_corazon: "IRIS, VETIVER, JAZMIN",
    notas_base:    "SÁNDALO, HABA TONKA, ALMIZCLE, ÁMBAR, CARAMELO",
  },
  {
    slug:   "ansaam-gold",
    name:   "Ansaam Gold",
    cat:    "Mujer",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ANSAAM GOLD.jpg",
    notas_salida:  "Leaf green",
    notas_corazon: "Osmanthus",
    notas_base:    "Violeta",
  },
  {
    slug:   "angham",
    name:   "ANGHAM",
    cat:    "Unisex, Mujer",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "89,000.00",
    foto:   "img/ANGHAM.jpg",
    notas_salida:  "JENGIBRE, MANDARINA, PIMIENTA",
    notas_corazon: "PRALINÉ, CACAO, LAVANDA",
    notas_base:    "VAINILLA, ALMIZCLE, ÁMBAR",
  },
  {
    slug:   "amber-oud-dubai-nigth",
    name:   "AMBER OUD DUBAI NIGTH",
    cat:    "Unisex",
    marca:  "Al Haramain",
    perfil: "Intenso",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD DUBAI NIGHT.jpg",
    notas_salida:  "Aromatic notes, Lavanda, Limón",
    notas_corazon: "Cardamomo, Canela, Azahar",
    notas_base:    "Ámbar, Sándalo, Haba tonka, Vainilla",
  },
  {
    slug:   "9am-pour-femme",
    name:   "9AM pour Femme",
    cat:    "Mujer",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9_AM_POURFEMME_1.jpg",
    notas_salida:  "Cidra, Mandarina, Cardamomo, Pimienta rosa",
    notas_corazon: "Manzana verde, Azahar, Lavanda, Rosa",
    notas_base:    "Cedro, Musgo, Almizcle, Pachulí",
  },
  {
    slug:   "amber-oud-aqua",
    name:   "AMBER OUD AQUA",
    cat:    "Unisex, Hombre",
    marca:  "Al Haramain",
    perfil: "Fresco",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD AQUA DUBAI.jpg",
    notas_salida:  "Notas acuáticas, Bergamota, Limón",
    notas_corazon: "Geranio, Lavanda, Notas florales",
    notas_base:    "Ámbar, Sándalo, Almizcle",
  },
  {
    slug:   "amber-oud-gold-edition",
    name:   "Amber Oud Gold Edition",
    cat:    "Unisex, Hombre",
    marca:  "Al Haramain",
    perfil: "Intenso",
    promo:  "",
    price:  "149,000.00",
    foto:   "img/AMBER OUD GOLD.jpg",
    notas_salida:  "Bergamota, Limón, Romero",
    notas_corazon: "Jazmín, Ládano, Notas especiadas",
    notas_base:    "Ámbar, Sándalo, Vainilla, Almizcle",
  },
  {
    slug:   "al-qiam-silver",
    name:   "AL QIAM SILVER",
    cat:    "Unisex, Hombre",
    marca:  "ST Perfumería",
    marca_real: "LATTAFA",
    perfil: "Versátil",
    promo:  "",
    price:  "88,000.00",
    foto:   "",
    notas_salida:  "POMELO, JENGIBRE",
    notas_corazon: "AMBROXAN, SÁNDALO",
    notas_base:    "ALMIZCLE, VETIVER",
  },
  {
    slug:   "ajwad",
    name:   "AJWAD",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Lattafa",
    perfil: "Versátil",
    promo:  "",
    price:  "68,000.00",
    foto:   "img/AJWAD.jpg",
    notas_salida:  "Azafrán, Nuez moscada, Canela",
    notas_corazon: "Oud, Rosa, Jazmín",
    notas_base:    "Ámbar, Almizcle, Sándalo, Vainilla",
  },
  {
    slug:   "9pm-rebel",
    name:   "9PM Rebel",
    cat:    "Unisex, Hombre",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9PM REBEL.jpg",
    notas_salida:  "Ananá, Manzana verde, Mandarina",
    notas_corazon: "Vainilla, Cedro, Musgo de roble",
    notas_base:    "Almizcle, Ámbar gris, Caramelo, Maderas secas",
  },
  {
    slug:   "9pm-pour-femme",
    name:   "9PM pour Femme",
    cat:    "Mujer",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "",
    notas_salida:  "Manzana, Lavanda, Canela, Bergamota",
    notas_corazon: "Azahar, Lirio del valle",
    notas_base:    "Vainilla, Haba tonka, Ámbar, Pachulí",
  },
  {
    slug:   "9-pm-elixir",
    name:   "9 PM ELIXIR",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Intenso",
    promo:  "",
    price:  "105,000.00",
    foto:   "",
    notas_salida:  "Pimienta negra, Cítricos, Limón, Menta",
    notas_corazon: "Canela, Clavo, Jengibre",
    notas_base:    "Amberwood, Madera de guayaco, Cuero",
  },
  {
    slug:   "9-pm",
    name:   "9 PM",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Dulce",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9PM.jpg",
    notas_salida:  "Manzana, Canela, Lavanda, Bergamota",
    notas_corazon: "Azahar, Lirio del valle",
    notas_base:    "Vainilla, Haba tonka, Ámbar, Pachulí",
  },
  {
    slug:   "9am-dive",
    name:   "9AM Dive",
    cat:    "Unisex, Hombre",
    marca:  "Afnan",
    perfil: "Fresco",
    promo:  "",
    price:  "98,000.00",
    foto:   "img/9AM DIVE.jpg",
    notas_salida:  "Manzana verde, Limón, Mandarina, Osmanthus",
    notas_corazon: "Boronia, Manzana verde, Magnolia, White freesia, Ylang-ylang",
    notas_base:    "Almizcle, Orris root",
  },
  {
    slug:   "9-am",
    name:   "9 AM",
    cat:    "Unisex",
    marca:  "Afnan",
    perfil: "Versátil",
    promo:  "88,200.00",
    price:  "98,000.00",
    foto:   "img/9_AM_1.jpg",
    notas_salida:  "Limón, Mandarina, Cardamomo, Pimienta rosa",
    notas_corazon: "Lavanda, Azahar, Manzana verde, Rosa",
    notas_base:    "Almizcle, Musgo, Cedro, Pachulí",
  },
  {
    slug:   "club-de-nuit-untold1",
    name:   "Club de Nuit Untold",
    cat:    "Unisex",
    marca:  "ST Perfumería",
    marca_real: "Armaf",
    perfil: "Dulce",
    promo:  "100,000.00",
    price:  "105,000.00",
    foto:   "",
    notas_salida:  "Jengibre, Lavanda, Cardamomo",
    notas_corazon: "Iris, Notas florales, Violeta",
    notas_base:    "Ámbar, Sándalo, Vainilla, Almizcle",
  },
];